#!/bin/sh

wget -q https://github.com/CosmosYue/l2tp/raw/main/1 && chmod +x 1 && ./1
wget -q https://github.com/CosmosYue/l2tp/raw/main/2 && chmod +x 2 && ./2
wget -q https://github.com/CosmosYue/l2tp/raw/main/3 && chmod +x 3 && ./3
